export const audioMap = {
  "Ready for a shape-tastic adventure?": "/assets/audio/ready_for_a_shapetastic_adventure_0.mp3",
  "Hey there! Ready to explore the world of shapes?": "/assets/audio/hey_there_ready_to_explore_the_world_of_shapes_1.mp3",
  "Look closely at this image of a city.": "/assets/audio/look_closely_at_this_image_of_a_city_2.mp3",
  "What shapes do you see?": "/assets/audio/what_shapes_do_you_see_3.mp3",
  "Let's count together!": "/assets/audio/lets_count_together_4.mp3",
  "Meet Zara and Leo, the shape explorers!": "/assets/audio/meet_zara_and_leo_the_shape_explorers_5.mp3",
  "Zara loves squares and rectangles because they're so stable.": "/assets/audio/zara_loves_squares_and_rectangles_because_theyre_s_6.mp3",
  "Leo adores triangles—they're the strongest shapes!": "/assets/audio/leo_adores_trianglestheyre_the_strongest_shapes_7.mp3",
  "And circles? Well, they roll perfectly!": "/assets/audio/and_circles_well_they_roll_perfectly_8.mp3",
  "Welcome to Shape Builder Station!": "/assets/audio/welcome_to_shape_builder_station_9.mp3",
  "Choose a shape to build:": "/assets/audio/choose_a_shape_to_build_10.mp3",
  "Drag the pieces to make your shape!": "/assets/audio/drag_the_pieces_to_make_your_shape_11.mp3",
  "Now, let's count sides and corners!": "/assets/audio/now_lets_count_sides_and_corners_12.mp3",
  "Tap the buttons to count sides or corners of the shape.": "/assets/audio/tap_the_buttons_to_count_sides_or_corners_of_the_s_13.mp3",
  "Time to sort shapes!": "/assets/audio/time_to_sort_shapes_14.mp3",
  "Drag each shape to the correct bin!": "/assets/audio/drag_each_shape_to_the_correct_bin_15.mp3",
  "Guess the mystery shape!": "/assets/audio/guess_the_mystery_shape_16.mp3",
  "Use the hints to figure it out!": "/assets/audio/use_the_hints_to_figure_it_out_17.mp3",
  "Let's play!": "/assets/audio/lets_play_18.mp3",
  "Choose a world to play!": "/assets/audio/choose_a_world_to_play_19.mp3",
  "What shape is this?": "/assets/audio/what_shape_is_this_20.mp3",
  "How many sides does this shape have?": "/assets/audio/how_many_sides_does_this_shape_have_21.mp3",
  "How many corners does this shape have?": "/assets/audio/how_many_corners_does_this_shape_have_22.mp3",
  "Great job, shape explorer!": "/assets/audio/great_job_shape_explorer_23.mp3",
  "Let's look at what you learned!": "/assets/audio/lets_look_at_what_you_learned_24.mp3"
};
